= Compiling the project

The project can be built for the Java 11.
To create a new release edit the `version.jim` file and set the

----
{@define VERSION=A.B.C}
----

line to whatever version is to be released.

The new version has to be propagated to the POM files.
To do that execute the command

----
mvn -f genpom.xml
----

To create a release the project has to be built first.
This is simply

----
mvn clean install
----

for the latest Java (Java 11 as for now),

The first run of the build will fail as the documentation still contains the old version.
Commit the changes and run the build command again.

The `genpom.xml` POM is executed by Maven before the build.
When the build starts the versions are already there in the different `pom.xml` files.

There is a test that checks that the version number in the POM files as well as in the `version.jim` file has or does not have the `-JVM8`
postfix.
If you compile for Java 8 and you do NOT have the postfix then the test will fail.
If you compile for a version that is later than Java 8 and there is the `-JVM8` postfix at the end of the version string then the test will fail.
The version must be consistent with the compilation target.

The tests also work following the Java::Geci philosophy: when the version is not appropriate then they remove or add the postfix.
They could also start the `mvn -f genpom.xml clean` command, but that is something they do not.
It is up to you execute the command or to revert the `version.jim` file and start a build for a different target in case it was not the version that was wrong but the build command line.

The last command to create the release is ```sh release.sh```.